version: 1
update_configs:
  - package_manager: docker
    directory: /
    update_schedule: daily
    allowed_updates:
      - match:
          dependency_type: all
          update_type: all

  - package_manager: javascript
    directory: /
    update_schedule: live
    allowed_updates:
      - match:
          dependency_type: all
          update_type: all
    version_requirement_updates: increase_versions
